### ISSUE TITLE
Show full type and direction in Address model

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#1]
The Address model (/swoptact/models.py) has two fields "type" and "direction."  The __str__() method returns the type and direction as their saved, abbreviated forms instead of as their longer names.  For example, we see "n" instead of "North."

**Comment by xray7224** [comment]
This has been fixed as of https://github.com/OpenTechStrategies/swoptact/commit/3a1a3da90b4e5ccbf696c9df3416e513fe874a43. Specifically I cache the choice defintion tuples as dictionaries and then whenever we need them to we can quickly look them up like we do in the `__str__` method now.
