### ISSUE TITLE
Sign-in sheet: Autocompletion with multiple options only allows users to choose the first

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#100]
This bug shows up when adding a new participant to the sign in sheet.  To reproduce: look at "International Women's Day," from the sample data.  Click "Add New," and enter "t" into the text box under the "Name" column.  Since there are multiple participants in the sample data that have "t" in their names, several names will show up.  However, instead of coming up as a vertical list that a user could choose from, each name appears next to all the other names as just one row of the dropdown menu, and the user can't choose from them.  Typing more letters solves this problem, since the autocompletion sorts correctly, but we should certainly be able to choose between results at all times.

**Comment by cwebber** [comment]
Done!  The string of html data that came back hadn't been wrapped/parsed into a jquery object before being cast into an array, hence being a single element.

It works now!
