### ISSUE TITLE
Migrations in an unresolved state

### ISSUE THREAD

**Issue by cwebber** [OpenTechStrategies/swoptact#102]
@cecilia-donnelly, could you sync up with me tomorrow on this one?  It looks like between both 1e8fb143e519d19efce55b541a07d64efc4faae2 (yours) and 61bacf8069bfd1ec8a9286027f0536d60ef527bb (mine) we are missing some migration steps on event/action.

However I'm not sure why the Django migration system is doing this, it looks like this really only should affect the python models, not SQL.  Anyway, we should talk and coordinate with what's going on.

**Comment by cecilia-donnelly** [comment]
I forgot to add a migration, and added it in 2adee5e.  I agree that it is strange that Django made a migration for that change.  Let me know if that fixes your issue.

**Comment by cecilia-donnelly** [comment]
@cwebber, I think this is fixed and am closing this.  Let me know if I'm wrong!
