### ISSUE TITLE
KeyError when entering "title" when adding participant on institution page

### ISSUE THREAD

**Issue by xray7224** [OpenTechStrategies/swoptact#103]
When you try and add a new participant on the institution page, the steps to reproduce are:

1) Navigate to a created institution
2) Press the "Add another Key Contact" button
3) Enter a value in the "Title" field
4) Hit "Save"

I think the solution is to check if the key exists in `self.data`, if it doesn't then we will want to skip that field, I haven't investigated further though.

**Comment by cwebber** [comment]
This may be papered over by this functionality being replaced with the work from #94 when complete, if I understand correctly.

**Comment by cecilia-donnelly** [comment]
Since I removed the Contact.title field in 27a61aa I'm going to close this one.  The Participant.title field will be addressed in #74 (which will also be affected by the #94 changes).
