### ISSUE TITLE
Institution: Clicking "Done" with open contact fails

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#104]
On the institution page, if a user clicks "Done" to save the form with an open contact (a new one, in this case), then they'll get an error page indicating a "MultiValueDictKeyError."

We should save the new contact when clicking "Done," I think.

To reproduce this, go to "Extra Venerable Institution," click "Add another Key Contact," then click "Done."

**Comment by cwebber** [comment]
Like #103 this bug may become irrelevant when #94 is done but I'm a little bit less sure about this one.

**Comment by cecilia-donnelly** [comment]
#94 changes have fixed this as of eba18a7.
