### ISSUE TITLE
Leaving page with unsaved changes should warn

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#107]
For all pages -- Institution, Participant, Action.

**Comment by xray7224** [comment]
We had an issue with firefox when tackling #47, firefox would only display their own custom message when preventing a page unload. I've discussed this with @cecilia-donnelly and she seems to think even though this is unideal it's better than nothing.

**Comment by cecilia-donnelly** [comment]
@xray7224 yup, full steam ahead on this.  Firefox will just display its default message and our custom message will appear on other browsers.

**Comment by cecilia-donnelly** [comment]
@xray7224 has this working for the simple cases and will manage more complex problems as part of #126.
