### ISSUE TITLE
Sign-in sheet: Don't expose id to users

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#109]
Currently, when we use the autocomplete menus, the participant or institution ID shows up in the text field until the user tabs away.  That will be confusing, so let's show the name instead.

**Comment by cwebber** [comment]
I believe this is fixed, but confirmation would be good!  Let me know if not.

**Comment by cecilia-donnelly** [comment]
It looks great for the institution, @cwebber, but it's still doing it for the participant (when you click "add new," start typing in the participant name text field, and choose a name from the autocomplete list of options).

**Comment by cwebber** [comment]
Hm, okay I'll look into that!

**Comment by cwebber** [comment]
@cecilia-donnelly What browser?

**Comment by cecilia-donnelly** [comment]
@cwebber on Iceweasel.

To reproduce: "Add New," then type "T" in the participant field, arrow down to "Theodore Rose," and a '14' shows up in the text box.

I'll take a look at this to see if I can see what to do about it, based on your commit 97e5a59.

**Comment by cecilia-donnelly** [comment]
Fixed in 192a127.
