### ISSUE TITLE
Sign-in sheet: Bottom/global "Done" button fails with creation of new institution

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#112]
When a user creates a new institution in an attendee row on the sign-in sheet and _doesn't_ save/close that row by clicking the row-specific "Done," then the bottom "Done" button fails to submit the form and exit the page (silently).  What should happen is that the bottom "Done" should save and close all open rows, as in #47, then save and exit the page.

**Comment by cwebber** [comment]
Fixed with #105
