### ISSUE TITLE
No longer able to save new participants

### ISSUE THREAD

**Issue by cwebber** [OpenTechStrategies/swoptact#120]
A bug appeared in the process of adding institution autocomplete to the ajax'y event/action forms where it is no longer possible to save new participants.  Obviously, this is a most serious bug.

I've narrowed down what's caused it, and am working on it.

**Comment by cwebber** [comment]
Fixed

**Comment by cecilia-donnelly** [comment]
@cwebber yay, thank you!  Is this the same as issue #111?
