### ISSUE TITLE
Temporary measure: change autocomplete "x" to pencil

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#123]
This will be changing, but currently on our autocomplete fields we have an "x" that removes an existing value and shows an input field (see #78).  Since we're changing how autocomplete works everywhere as part of #94, this will be going away, but for now let's change the "x" to something that more clearly indicates that we're *editing* instead of deleting.

**Comment by nttaylor** [comment]
Can be closed, I believe, following 3f9b9f0

**Comment by cecilia-donnelly** [comment]
@nttaylor hey, nice!
