### ISSUE TITLE
Contacts: Creating a new Participant as a contact fails

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#129]
On the sign-in sheet, we can create an entirely new-to-the-db Participant and link that new Participant to the event.  I believe we ought to be able to do the same thing on the Contacts page (yes?), but we can't yet.
Currently, if I enter a name that does not exist in the database ("Jay Random") as a Contact and click "Done" in that row, nothing happens.  Looking at the response shows a `404: Page not found at /api/contacts/`.  I think we just aren't enabling Participant creation via Contact page yet, but we should.

**Comment by cecilia-donnelly** [comment]
Assigning @cwebber for now, but this might be a job for @xray7224.  Let's discuss.

**Comment by cwebber** [comment]
Yes, /api/contacts/ never existed... I actually noticed this while working on #20 ... I meant to add logging there but discovered it pointed at an endpoint that never existed.

Unfortunately, this is held up by #203, so I will work on that one first.

**Comment by cwebber** [comment]
Now that #203 is done, this was a piece of cake!  I just subclassed the participants create view because... well technically "contacts" still are participants, just with different fields on a different other form.

**Comment by cecilia-donnelly** [comment]
Thanks, @cwebber!  Glad this wasn't too complicated.
