### ISSUE TITLE
Sign-in sheet: Click to edit

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#135]
Remove "Edit" button.  Instead, allow users to click into a field to edit that field (e.g., clicking on the static name will bring up a text box with the name prefilled, for editing).  I imagine that clicking away would then save the changes made.  @kfogel does that sound right?

**Comment by nttaylor** [comment]
This is working following 7176e15 which merged branch 135-click-to-edit into master.
