### ISSUE TITLE
User Groups: Restrict access for leaders

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#138]
There is some confusion between the "organizer," "leader," and "data entry" groups, in our communication with the end users.

That being said, we need to set up the following permissions for a "data entry" user group (currently called our "leader" group) that has the following restrictions:

1. No delete/archive (see #32) buttons
2. No tag creation
3. Can only use tags available to the "leader" group
4. Has no "Change password" option

**Comment by cecilia-donnelly** [comment]
Note while we're doing user administration:

Admins only have access to:
1. Archive
2. Tag creation

**Comment by cecilia-donnelly** [comment]
@xray7224:
Only "admins" (top level users) should have access to group and user administration.  Ideally, no one else would even see links to that section.

**Comment by cecilia-donnelly** [comment]
And see #43 for another restriction!  Everyone can view contacts, but only admins can add them.

**Comment by cecilia-donnelly** [comment]
@xray7224:

Okay, so I looked into this a bit just now and it looks like we want the leader group to have only these permissions:

- can add action
- can change action
- can add institution
- can change institution
- can add participant
- can change participant

Is there any way that you know of to set these in the code, or do we need to use the web interface to set them for each server we set up?

In either case, we do need to use the code to restrict the view of "Change Password," and to only use the correct tags.

**Comment by xray7224** [comment]
I've committed what I think is enough to fix and close this issue, I'll move it over to master once @cecilia-donnelly has reviewed to ensure it'd what she was expecting.

**Comment by cecilia-donnelly** [comment]
To clarify, the three groups are:

1. admin
2. staff
3. leader

In the first comment on this issue I mentioned renaming "data entry" to "leader."  Issue #152 was about renaming "organizer" to "staff."  After these changes, the three groups above are the only groups we need.
