### ISSUE TITLE
Activity Log: Are we storing information on who made a given change?

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#139]
Could we find out who did a certain piece of data entry?  I think we do have that information, but we should find out for sure (and how to retrieve it).

**Comment by xray7224** [comment]
Django's ActivityLog stores this:
- Who did something (User)
- The object they did it on (but **not** what changed on the object)
- When the activity occured

If you want to do a `git blame`-esk system that isn't possible with what is currently recorded.

Finally to get to this data you have it all in the LogEntry model provided in the `admin` app:
```python
from django.contrib.auth import get_user_model
from django.contrib.admin.models import LogEntry
from django.contrib.contenttypes.models import ContentType

tsyesika = get_user_model.objects.get(username="tsyesika")
event_ct =  ContentType.objects.get(
    app_label="swoptact",
    model="event"
)

# Find all activities from tsyesika that occured on the Event/Action
events = admin_models.LogEntry.objects.filter(
    content_type=event_ct,
    user=tsyesika
)
```

([source: Activity model in Django's source code](https://github.com/django/django/blob/1.8c1/django/contrib/admin/models.py))

**Comment by cecilia-donnelly** [comment]
After work in #20, I think I can close this.  We're  not storing absolutely everything about changes, but we're storing enough.
