### ISSUE TITLE
Position "Create New" button all the way to the left

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#144]
After  #130 and the changes leading up to it, the users decided that they wanted this button at the far left anyway.

**Comment by nttaylor** [comment]
![screen shot 2015-08-03 at 4 45 37 pm](https://cloud.githubusercontent.com/assets/12848962/9048479/2e975c4a-39ff-11e5-82c6-517271c2c79f.png)

**Comment by nttaylor** [comment]
see also...
![screen shot 2015-08-03 at 4 47 59 pm](https://cloud.githubusercontent.com/assets/12848962/9048525/78fd4b32-39ff-11e5-94f5-69034b1a7e79.png)

**Comment by nttaylor** [comment]
Closing following 6970b74
