### ISSUE TITLE
Inlined Models: autocompletion is no longer available after tab away

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#148]
I saw this on the sign-in sheet, specifically.  To reproduce:
- Click "Add New"
- Start typing a name and choose it from the autocompletion dropdown options
- Tab to the next field
- Click back to the name field

I would expect the name field to still have autocompletion, but it does not.  I think this is related to #110, and maybe we should all talk about it more.
@cwebber @kfogel

**Comment by cwebber** [comment]
@cecilia-donnelly Can you double check that this problem exists?  I just tested and it works here...

**Comment by cecilia-donnelly** [comment]
@cwebber will do!

**Comment by cecilia-donnelly** [comment]
@cwebber you're right, this is working fine!  Closing now.
