### ISSUE TITLE
Remove "is_staff" requirement to login?

### ISSUE THREAD

**Issue by xray7224** [OpenTechStrategies/swoptact#156]
Django admin by default only allows people marked as "staff" to login to the Django admin interface however, since the entire site is build ontop of the admin UI it seems that this flag is pointless as it must be set on every user right now.

I propose we remove the requirement to be staff to login to the admin UI and remove the "staff" field when editing users.

**Comment by cecilia-donnelly** [comment]
@xray7224 yes, that sounds great.  I too noticed that every user needs to be staff.  Please go ahead and make that change!
