### ISSUE TITLE
Reunify change list template

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#160]
Currently, we have two change list templates: one is "with headers" and the other is "without headers."  The files are `change_list.html` and `change_list_without_header.html`.  These should be consolidated back into one template, so that we only have to make changes in one place.

**Comment by nttaylor** [comment]
Closed following 4a7ee36. Checking the model in `change_list.html` and acting accordingly is a DRYer solution to the problem of sending header-less tables to the user.
