### ISSUE TITLE
Inlined models: Pressing "add new" button adds row out of view of user

### ISSUE THREAD

**Issue by cwebber** [OpenTechStrategies/swoptact#161]
I pressed [+ Add New] on an inline row and was getting frustrated because I thought it wasn't appearing.  However, the row did appear.... invisibly, at the bottom of the list, which was out of view.

@nttaylor has offered to fix this one!

**Comment by nttaylor** [comment]
I believe this should be fixed following 7176e15. Clicking "add new" now not only adds a row for input, but puts the focus on the first `<input>` element in that row, which means the window will scroll if necessary. I'm cautiously closing this issue and will wait to see if others' experiences are the same as mine.
