### ISSUE TITLE
Sign-in sheet: use i-in-a-circle ("(i)") instead of Unicode "i" glyph, for Participant information link.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/swoptact#162]
In `swoptact/templates/admin/institution_contacts_inline_tabular.html` we are currently using "`&#x2139`" (the Unicode "i for information") to produce an information-link glyph next to the participant's name.  A standard i-in-a-circle would look better.

Athough there exists a Unicode code point for i-in-a-circle ("`&#x1F6C8`"), it's not widely supported in browsers yet, as it was only introduced in 2014 -- indeed, my recent Firefox 38.1.0 still displays it as a broken glyph.  (See https://www.emojibase.com/emoji/1f6c8/circledinformationsource for more information and to test how your browser does.)

So we should use an image.  Commit 42d436739 offers a possible starting point.

**Comment by nttaylor** [comment]
Cautiously closing following d62d1fa. Why cautiously? I think everything should look all right on other users' browsers, but you can never be sure until they tell you.
