### ISSUE TITLE
"Leader" users can't add/edit attendees

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#163]
In commit 69e136b, we set the UI so that users without permission to add/edit *contacts* wouldn't see the relevant UI elements.  However, that inadvertently removed those elements for the sign-in sheet, as well (because they are governed by the same file, inline_ajax.js).  Now, leaders cannot edit or add users to the sign-in sheet.

I should have caught this earlier, but it definitely needs to be fixed.  The main purpose of the "leader" user group is to add and edit entries on the sign-in sheet!  @nttaylor has begun to set up some architecture to address this in commit 7176e15.

**Comment by nttaylor** [comment]
This functionality implemented in c40cbc1. At least one bug remains, which is that "leader" users do not see the "add new" button on the change events page (and they should see it). See commit message for further details.

**Comment by nttaylor** [comment]
This issue now closed. The bug noted above now has its own issue #168
