### ISSUE TITLE
Adding inlined model creates new instead of linking to existing

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#167]
On the sign-in sheet, since the click-to-edit changes, adding a participant by selecting a choice from the autocomplete is creating a new Participant object instead of linking the existing Participant object to the Action.  This is a regression, so we should figure out where it happened and fix it.

The problem seems to be in the `saveInlinedModel()` function.  It can't find the `inlined_model_id`, since row.data is empty or doesn't have the correct information.  It looks to me like the object ID is not being set in row.data when a Participant is selected from the autocomplete.  So, this might be fast for someone  ( @nttaylor?) who knows where to look.

**Comment by cecilia-donnelly** [comment]
@nttaylor see my commit comment in 5a8fb42.  It's not fixed, but I think I understand what's happening.  Hopefully I explained clearly!

**Comment by nttaylor** [comment]
Closed following de9b3f9. Entering a name with autocomplete no longer creates a new entity. However, problems remain for which new issues will be created:
1. Entering a name with autocomplete causes a row to appear in the ajax table even if the entity represented in that row already appears elsewhere in the table. Even though the new row points correctly to the original entity, the same entity should not be represented by multiple rows in the same table. We need a way to warn the user about this.
2. Typing in a name character-for-character as it appears in an autocomplete option (but not actually using autocomplete) does cause a new entity to be created. This might be correct behavior if the new entity represents a new person who happens to have the same name as someone already in the DB, but again we need a way to alert the user to this.
