### ISSUE TITLE
Inlined models: phone number is no longer validated

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#170]
The inlined models should return an error if an invalid phone number is entered.  They had been doing this before the #135 changes, which changed much of the behavior of these fields.  So, looking back at earlier commits should show us how to restore that error.

Currently, invalid phone numbers just disappear on refresh of the page because the client accepts them but the server refuses to save them.

**Comment by nttaylor** [comment]
Error messages for invalid phone numbers are once again displayed. This issue closed following 922ea84.
