### ISSUE TITLE
Adding tag from action page that doesn't exist should give friendly error

### ISSUE THREAD

**Issue by cwebber** [OpenTechStrategies/swoptact#172]
I tried adding a tag that doesn't exist to the Actions page.  I figured this would make the tag for me, hence filing #171.  However, it exploded into an exception!  If we're not going to permit new tags in this interface, we should be giving users a friendly indication that their input is invalid (preferably both before and after submission).

**Comment by cecilia-donnelly** [comment]
In case anyone is interested, this is the start of the exception:

>IntegrityError at /swoptact/event/8/

>NOT NULL constraint failed: swoptact_tag.group_id

**Comment by cwebber** [comment]
Right, so here's the problem... tags are foreign key'ed to auth_models.Group, and if you add a new tag, it doesn't know what "Group which can use this tag" to add it to.  I'm not sure what solution there is.

How is the tag group administration handled anyway?  I don't see anywhere a group policy is enforced, though I must be missing it I assume?

**Comment by cecilia-donnelly** [comment]
Ah, so: we should not allow adding a new tag from this page.  I thought this issue was just about giving a friendly error, something like: "This tag does not exist.  If you are an administrator, go to the New Tag page to create a tag."

**Comment by cecilia-donnelly** [comment]
@xray7224 created a policy that controls which tags a given group can use.  I think it's the "AvailableTagsAPI" in `views.py`.

**Comment by cwebber** [comment]
@cecilia-donnelly I see.  The AutoCompleteModelForm logic is currently set up to add new models and save them if they do not exist.  We can change this, but in its own way I think this will be also unexpected behavior UX-wise: if you enter tags into a form, there is no explicit statement that they will not be added, and then you save and they disappear, when is the user indicated why this happened?

Also, we should decide if this is the behavior for everything we wish to use with AutoCompleteModelForm, or if the "don't save new things" only applies to tags.

**Comment by cecilia-donnelly** [comment]
@cwebber I think we do want to explicitly state that they will not be added.  Ideally, to my mind, the same kind of error that pops up with other invalid input would appear, telling the user that they can't add a tag from that page.  In most cases, they won't be allowed to add a tag at all.

I think "don't save new things" only applies to tags, because the client wants stricter control over who can create them.

**Comment by cwebber** [comment]
@cecilia-donnelly Okay, that helps, thanks!

**Comment by cwebber** [comment]
This is, again, useful information to know.  Particularly since this may mean that we need to make some adjustments accordingly, see this docstring:

```
class AutoCompleteModelForm(forms.ModelForm):
    """ Creation of new objects from text field of autocomplete fields

    When a field is using an autocomplete field and the object they're entering
    has not been created, this will create the object if the field is the only
    required field to create the object. If the object has other required fields
    this will not provide this functionality.
    """
```

I'm out till Tuesday, but should resume it then!

**Comment by cwebber** [comment]
Okay, since "don't create" only applies to tags, I added a structure so that users can specify which users they want to skip for autocreate.  This is now committed and pushed to master.  I also added some helptext.  It may not be aligned exactly where expected (I personally expected it under the widget) but I think that may be a separate issue.

**Comment by cecilia-donnelly** [comment]
@kfogel points out that we're still not showing an error here (we're just blowing away any entered information).  The correct behavior here is to show an error as soon as the user removes focus on the field, if they've entered a tag that doesn't exist.  This can be shared with our work on #205, most likely -- we really want to show a clear error as soon as possible, rather than ambiguous help text.
