### ISSUE TITLE
Users: Hide password algorithm and hash

### ISSUE THREAD

**Issue by nttaylor** [OpenTechStrategies/swoptact#175]
When a new user is created, the logged-in administrative-level user sees:

"algorithm: pbkdf2_sha256 iterations: 20000 salt: 1660Bm****** hash: iXbU2s**************************************"

This is probably not desirable.

**Comment by cecilia-donnelly** [comment]
In fact, the admin user should also not see the user permissions.  They should only be able to assign a new user to a group.  Nor should they have the "superuser" option visible.

**Comment by nttaylor** [comment]
Closed following 067282e.

**Comment by cecilia-donnelly** [comment]
I reverted cecda53 in 4ba43de because it had some unintended effects, but we now need to come up with the correct solution to this issue.

**Comment by cecilia-donnelly** [comment]
See #179, which is a more specific explanation of [my earlier comment](https://github.com/OpenTechStrategies/swoptact/issues/175#issuecomment-132291950).
