### ISSUE TITLE
Inlined models: No way to cancel out of adding a new user anymore

### ISSUE THREAD

**Issue by cwebber** [OpenTechStrategies/swoptact#177]
Since the changes to make fields click-to-edit, there's no way to cancel out of adding a new user any more.  It looks like API queries are being thrown to models which of course do not exist.

The previous code had behavior so that a "new" row when being removed would not make an API request but just remove its rows.

**Comment by nttaylor** [comment]
Can possibly be closed following 070ac87, but requires further testing.

**Comment by cecilia-donnelly** [comment]
Looks done to me.
