### ISSUE TITLE
Models: add audit trail

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#20]
Add timestamped log of all things that happen in the database (adding a new object, associating a Participant to an Action, etc).

**Comment by cecilia-donnelly** [comment]
@kfogel, this came up again in today's demo.  Let's discuss and add a plan to this issue.

**Comment by kfogel** [comment]
Okay, looks like this exists already -- Django's been doing it for us.  Look for a table named `django_admin_log`.  I asked sqlite3 about the table:

        $ sqlite3 swoptact_db
        sqlite> .tables
        auth_group                   swoptact_address           
        auth_group_permissions       swoptact_contact           
        auth_permission              swoptact_event             
        auth_user                    swoptact_event_participants
        auth_user_groups             swoptact_event_tags        
        auth_user_user_permissions   swoptact_institution       
        django_admin_log             swoptact_institution_tags  
        django_content_type          swoptact_participant       
        django_migrations            swoptact_tag               
        django_session             
        $ .schema django_admin_log
        CREATE TABLE "django_admin_log"
        ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
         "action_time" datetime NOT NULL, 
         "object_id" text NULL,
         "object_repr" varchar(200) NOT NULL,
         "action_flag" smallint unsigned NOT NULL,
         "change_message" text NOT NULL,
         "content_type_id" integer NULL REFERENCES "django_content_type" ("id"),
         "user_id" integer NOT NULL REFERENCES "auth_user" ("id"));
        CREATE INDEX [...rest not interesting here...]

The only question now is, what's the right Django-y way to access that data?  (I presume just running raw SQL queries is *not* how the cool kids do it!)

**Comment by kfogel** [comment]
Okay, these seem like the right places to start learning:

http://stackoverflow.com/questions/987669/tying-in-to-django-admins-model-history
http://stackoverflow.com/questions/3157875/logging-activity-on-djangos-admin-django
http://www.mc706.com/tip_trick_snippets/10/recent-actions-using-django-admin-log

**Comment by xray7224** [comment]
We could do this with some template changes and styling. The part you will be taking is https://github.com/django/django/blob/1.8c1/django/contrib/admin/templates/admin/index.html#L55 there looks to be a `sidebar` block you will have to copy and paste over to our templates, this will show the recent changes.

I don't believe Django provides a view to look through these past the [little sidebar](http://vinylproject.com/dp/files/washtub-screens-admin.jpg), to do that you would have to create a new django admin page by registering the model, you probably wouldn't want people editing or deleting the logs through so you'd probably want to make it so it was read only.

**Comment by cwebber** [comment]
This shares a lot of the issues / concerns I raised in #16.  I guess it would be helpful to know scope.  Is showing the stuff currently in that audit system, but just on specific models pages, sufficient?  I am guessing no for the reasons of AJAX'y type stuff and other things likely not captured or displayed well.

[This link](http://www.mc706.com/tip_trick_snippets/10/recent-actions-using-django-admin-log/) posted by @kfogel above makes me think the data here is really not structured... the "content map" part of the code shown in that blogpost indicates to me that there's no firm way to extract that data, and I wonder if there's no guarantee that the integers in the database map to certain locations, which could result in us writing some shoddy code.  But I don't fully understand things yet.

I think we have to be prepared that we will either just go with what django already provides and not try to get anything more out of it than it gives (a basic visual log), and we could start appending to that, though it's possible that we're going to have to do something more complex to make this happen, which might result in having to have our own log appending functions hooked onto certain admin and API procedures.

**Comment by cecilia-donnelly** [comment]
Thanks for this, @cwebber.  I think we can try starting with the basic visual log, perhaps with a date filter.  As I mentioned in IRC, this might almost be a duplicate of #16.  I think both issues (and #17) are getting at a desire from users to be able to look at the kind of data that is being changed in a given week or other time period.

So, for now: let's go with what Django provides and look into how difficult it would be to include data added with our `inlined_models`/AJAX-y interfaces.

**Comment by cecilia-donnelly** [comment]
@kfogel I need your thoughts on this one.  I think the other issues are fine and well-sorted into milestones, but we should chat about whether this goes in Phase 1 or 2.

**Comment by cecilia-donnelly** [comment]
After talking with @kfogel, the important part of this issue is ensuring that we're tracking these changes.  It's okay if we don't have a view for accessing the information right away, but we should make sure that we're not losing it, so that we can get it for them later, if they want it.

**Comment by cecilia-donnelly** [comment]
@cwebber and I looked at what Django is already doing.  It saves some basic information about each change: the object that was changed, the user that made the change, and a string description of the change itself.  That's enough information for our purposes, and saving any more detailed data would require a much bigger project than we have time for here!

Django isn't currently picking up changes made via our custom AJAX-based interfaces (the inlined model forms) or, perhaps, through autocomplete.  @cwebber will look into what information isn't being saved and then will add hooks to save it to the log in the same form as the other entries.

**Comment by cwebber** [comment]
This is now done, including for linking/unlinking models.  The messages are not great when editing the fields via the interface, because currently all fields are blasted to an object at once for legacy reasons.  If we update the code to only update one field at a time appropriately, we can say exactly what field we are updating in the log.

Otherwise, done!
