### ISSUE TITLE
Some tweaks necessary with new background

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#202]
When we archive an object, Django gives us a message saying "`<object>` was archived successfully."  With the new background image, that message is hard to see.  In the screenshot below, it's right under the breadcrumb.

![screenshot from 2015-09-21 13-04-26](https://cloud.githubusercontent.com/assets/1497818/10000377/640b86d4-6061-11e5-830e-fd9541476127.png)

**Comment by cecilia-donnelly** [comment]
Group permissions hang off the side of the page with new background:

![screenshot from 2015-09-21 13-16-45](https://cloud.githubusercontent.com/assets/1497818/10000649/15645dba-6063-11e5-8105-c7f44856656a.png)

**Comment by cecilia-donnelly** [comment]
Log in screen is cramped.  We need a little padding between the labels and the fields.  I think the username field could be a little bigger, too.

![screenshot from 2015-09-21 13-19-21](https://cloud.githubusercontent.com/assets/1497818/10000690/69b51d78-6063-11e5-8da1-f208e935dd8e.png)

**Comment by cecilia-donnelly** [comment]
"SWOPtact Administration" title shows up twice.

![screenshot from 2015-09-21 13-50-09](https://cloud.githubusercontent.com/assets/1497818/10001566/f3847ab8-6067-11e5-8a13-f6c48b91c2c1.png)

**Comment by nttaylor** [comment]
Closed following commits f9f7fa2, 2abefa2, 7242b08, eb6dee4, and 75eb94c
