### ISSUE TITLE
Creating contact on Institution page fails

### ISSUE THREAD

**Issue by cwebber** [OpenTechStrategies/swoptact#203]
This is similar to but separate in nature from #129, which is hitting a 404 (the api view it was connected to never existed).  In this case, this *used to* work, but has sometime recently broken.  My guess is it broke when we switched from editing a whole row at a time to single-field editing, but we'll see.... about to kick off a git-bisect.

**Comment by cwebber** [comment]
Guess who broke it!  I broke it while working on #20, go figure.  Looking into why this broke...

**Comment by cwebber** [comment]
Okay, so here's the deal... all the logging code needs the object that it's referencing.  The code I added for logging works fine for updating, linking and unlinking, but is buested on object creation because it calls self.get_object() and there *is no* self.get_object() at this point.

So I need to call from somewhere in the code where the object is known.  Looking at figuring out how to do this.

**Comment by cwebber** [comment]
Sorry, multiple inheritance + mixins is a recipe for "@cwebber can't figure out how to put things in the right place" :(

I'm going to give up and go the sloppy spaghetti route :\

**Comment by cwebber** [comment]
Okay, I fixed this.  It's very complicated to explain why I had to take such a messy approach to this, but basically there was no way to keep the right information around at the right place to do this in a nice and non-horrible way.  So I did it the horrible way... :\

Anyway, things work now.  I wish I didn't have to do things the way I did, but I can't wrap my head around any other solution given multiple inheritance diamond problems.  I might just be missing something.  Adjustments are most welcome.

**Comment by cecilia-donnelly** [comment]
Hey, @cwebber: would you mind adding a little documentation about things we need to look out for in future around logging?  It seems like adding new API endpoints or models will require us to add logging, right?  Can you write that down in a DESIGN.md or similar?

Thanks!
