### ISSUE TITLE
Add user administration and meaningful groups

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#21]
Swoptact needs at least two different access levels.  One is a volunteer/data-entry level that can only enter data.  The other is an administrator level that can archive information and add/change users.

**Comment by cecilia-donnelly** [comment]
More on this, related to issue #27:
- admin (primary): can create/alter user accounts, create, archive, and use all tags
- organizers (secondary): can use certain tags
- leaders (tertiary): basic search, basic entry, and basic tags (probably 5 major issue areas: housing, education, immigration, violence prevention, health [?])

**Comment by cecilia-donnelly** [comment]
@xray7224, this looks done to me.  Is it?

**Comment by xray7224** [comment]
I think so, we can always re-open if we find it isn't.
