### ISSUE TITLE
"welcome" message breaks look and feel on smaller screen sizes

### ISSUE THREAD

**Issue by nttaylor** [OpenTechStrategies/swoptact#212]
On smaller screen sizes, the "welcome" message that should appear to the left of the "hamburger" (three lines) icon in the upper right corner gets pushed down into the purple nav bar, where it is only barely visible. The search bar also gets pushed to the bottom of the now too-thick nav bar.
![screenshot](https://cloud.githubusercontent.com/assets/12848962/10112713/1b5b0ea6-63a3-11e5-9803-9088a0727bf0.png)

**Comment by cecilia-donnelly** [comment]
@nttaylor Ooh, good catch.  Sorry for not testing this fully.
