### ISSUE TITLE
Change lists: make archived filtering more intuitive

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#224]
- [ ] "All" should be at top of list
- [ ] Show a checkmark next to the selected option
- [x] Use "show only active" and "show only archived" and "show all"
- [x] Remove "by archive status"

**Comment by cecilia-donnelly** [comment]
Done as part of the #250 work.  I decided not to move "All" to the top because the default is to show only active and I think the default should be the first option.

I'm not showing a checkmark because now that we're using a dropdown the selected option is displayed.

**Comment by kfogel** [comment]
On Oct 22, 2015 5:28 AM, "Cecilia Donnelly" <notifications@github.com>
wrote:
>
> Done as part of the #250 work. I decided not to move "All" to the top
because the default is to show only active and I think the default should
be the first option.

+1 -- makes sense to me!
