### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#24]
On the front page, add a generic search field that takes a string and returns a list of actions, institutions, and participants that match that string.

**Comment by cecilia-donnelly** [comment]
@xray7224 I'm guessing this is simple for you, so I'm assigning you -- is that true?

**Comment by cwebber** [comment]
Doing this across one model is kind of easy, and can use django's own tools.  Doing this across multiple models requires us rolling our own view, which is certainly feasible.

**Comment by cwebber** [comment]
We're getting into the territory of extending Django's admin beyond the very simple CRUD-minimal tasks it was designed for.  That's okay, because Django was designed for much more than its admin, but we should be aware that things don't come free anymore past this point!

**Comment by kfogel** [comment]
A combined view of a search across N models should be *pretty* trivial, right?  (Or am I missing something?)

What I mean is, let's multiplex the search.  Have one search input box in the upper right, and when someone enters a string, we execute the search for each model -- that is, N searches where N is the number of models -- and present the combined results.  Perhaps even present them columnarly, but even just a list of results with each result labeled with with the type of model it comes from is fine.

So there would be a custom-rolled view here, but it's a pretty trivial view to roll, I would think.

Can we get global search for "nearly free" this way, or is there a wrinkle I'm not aware of?

**Comment by cecilia-donnelly** [comment]
@cwebber @xray7224:

User stories for search:

Sandra is an organizer at SWOP who has a general understanding of the different campaigns (sets of actions) that SWOP is working on.  She needs information about specific people that she is meeting with, and meta information about participation across actions and sets of actions.  For all of these searches, the time period may be specified or unspecified.  It might be a grant period or the past year, or any pair of dates.

- Sandra needs to find Theodore Rose's phone number, so she searches for him and looks at his record.
- Sandra wants to see a list and count of people who have been involved in the set of actions planned by a given organizer within a period of time.
- Sandra wants to see a list and count of the people who attended a given action.
- Sandra needs to find a list and count of people who attended actions leading up to a given "major action" within a period of time.
- Sandra wants a list of the institutions whose members attended a given action.
- Sandra wants a list of the institutions whose members attended actions leading up to a given "major action" within a period of time.

Allie is an admin at SWOP who needs meta information about participation in actions and sets of actions across SWOP in order to report to funders.  She needs everything that Sandra needs, as well as:

- Allie needs a list and count of the people who attended actions with a given tag within a period of time.
- Allie needs a list and count of the institutions whose members attended actions with a given tag.

**Comment by cecilia-donnelly** [comment]
@xray7224 suggests looking at https://github.com/etianen/django-watson.  She's already using it in another project.

**Comment by cwebber** [comment]
@kfogel it's not so hard, it's just not as dead-easy as adding an attribute the way many built-in admin things are.

**Comment by cecilia-donnelly** [comment]
This is thrilling!  One note about the basic search: the search box is visible before user logs in (on homepage, at top right).

**Comment by xray7224** [comment]
Fixed that problem

**Comment by cecilia-donnelly** [comment]
We've been using "basic" and "advanced" to describe the two kinds of searches that we expect users to make.  The "basic" search is already working on the 24-add-search as of 4d27a25.  That search is what is discussed in the first comments in this issue.  The "basic" search "takes a string and returns a list of actions, institutions, and participants that match that string" as I originally described it.

Then I [added a list of user stories](https://github.com/OpenTechStrategies/swoptact/issues/24#issuecomment-130368212) and we realized that these really merited an "advanced search" option.  @xray7224 and I talked about this in IRC briefly, but didn't go into the UI very much.

[This looks like a nice UI](http://ux.stackexchange.com/questions/60999/is-there-a-correct-ui-pattern-for-advanced-search/61000#61000), and perhaps @nttaylor and @cwebber have ideas about the best way to present the "advanced search" options.  I think the searching will mostly be done on desktops, unlike the data entry.  

Perhaps Watson already helps with UI, so this won't be as much of a problem, but just in case: I could also see using list-type search, where users can click into and out of certain options, [like the first image in this answer](http://ux.stackexchange.com/a/22282) (not the too-busy diamond search).

**Comment by kfogel** [comment]
Makes sense, but I think we should hold off on the advanced search until we see how much it's really needed.  It might well be that plain search, with properly annotated results, gets the customer 90% of what they need anyway.

**Comment by cecilia-donnelly** [comment]
After talking to @kfogel, we're going to go ahead on this.

**Comment by cecilia-donnelly** [comment]
@xray7224 has finished the basic search, so I'm going to close this and open a separate issue for "advanced search."

**Comment by cecilia-donnelly** [comment]
Merged to master in 04589ba
