### ISSUE TITLE
Report: Sort by tags

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#26]
Search and report on Actions by one or more tags.  Users will also want to filter by a date range.  (More to come on this, just wanted to note that it will be necessary)

**Comment by cwebber** [comment]
This is easy, can use django's own builtin features!

**Comment by cwebber** [comment]
This is being blocked by #171

**Comment by cwebber** [comment]
Okay, resolved!  There's now a sidebar that lists all tags on the Actions page.  (This was very simple once I stopped being confused by #171/#172)

This might not be a permanently ideal solution though; if many tags are added this list is sure to become very large.  What do you think @cecilia-donnelly?
