### ISSUE TITLE
Have a tagging system (used with Actions first)

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#27]
For now, SWOP will add tags to Actions.  SWOP may later expand tagging to Participants and Institutions.

This system would be for admin users, who will control tag namespace and use them for reporting (possible tags: “housing,” “TTM”). The number of tags is unlimited. New tags are defined by admin users.

**Comment by cecilia-donnelly** [comment]
More conversation with users brought up these notes:
- tags will be a maximum of 10 chars and may also include with a longer description field
- tags are not just for events but also institutions
- will need an explicit creation UI, including choosing the user level necessary to use a specific tag (some tags will be restricted to the admin level of access, and basic data entry people will only be able to use a few general tags)

**Comment by cecilia-donnelly** [comment]
I'm imagining tags will be their own model and will have m2m relationships with events and institutions.  I'm not entirely sure how to handle the UI, especially the access levels piece.

**Comment by cecilia-donnelly** [comment]
UI:
Adding tags will happen only on an access-controlled page.  Note that "organizers" are usually staff members who aren't admins and "leaders" are volunteers doing data entry.  This page will look something like this:

```
Tag name: |________| // (10 chars or less)
Tag description: |____________________| // (perhaps 255 chars)
Tag is usable by:
|_| Administrators
|_| Organizers
|_| Leaders

|Create tag|
```

Then on an event or institution profile, we'll see a text field with completion options that appear once a user starts typing a tag:

```
Tag(s): |m______|
            magpie
            miraculous
```

For now, if it's easier, we'll just allow them to add one tag.  In the future, though, they should be able to add as many as they like.

**Comment by cecilia-donnelly** [comment]
@xray7224 and I will be working on this together, much as we did with 13.  I will need an api that takes the logged-in-user's group(s) and returns the set of tags available to that user.

I'll then take the response, create a jquery array, and use the autocomplete widget (http://api.jqueryui.com/autocomplete/) to show available matching tags to the user once they start typing.

@xray7224 points out that the complex part of this will be assigning tags to user groups.  We think we'll need a field in the tag that corresponds to the group or groups to whom the tag will be available.  Note that there will never be a case where a tag is available to leaders and not to administrators.  That is, access to tags cascades upward -- administrators can use all, organizers many, and leaders only a few.

**Comment by cecilia-donnelly** [comment]
- [ ] reorder groups in dropdown so that they match the order of hierarchy (admin, organizer, leader)
- [ ] rename "group" to "group assignment"

**Comment by cecilia-donnelly** [comment]
@xray7224, currently the api uses a user_id provided by the front-end js.  I think we'll always want the set of tags available to the currently logged-in user, so let's use the logged-in user's user id when fetching the set of available tags.

**Comment by xray7224** [comment]
This has been done @cecilia-donnelly, the new URL is `/api/current/available-tags/`

**Comment by cecilia-donnelly** [comment]
@xray7224, thank you!
