### ISSUE TITLE
Parse addresses properly

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#29]

**Comment by cecilia-donnelly** [comment]
After our adventures researching inline admin last week, I'm no longer sure that it is the right way to do this (it goes the wrong way -- we could edit participants on an address page, but not vice versa), but the point stands.  The address should be add-able and edit-able from the participant page, including the zipcode, city, state, and other fields we've added.

**Comment by cecilia-donnelly** [comment]
Similarly, we ought to be able to edit and add addresses from the event sign-in-sheet (#13).

**Comment by cecilia-donnelly** [comment]
We should look into this new library from our friends at Datamade: http://datamade.us/blog/parsing-addresses-with-usaddress/

It will help us transform a text field (easy for users) into an address object (easy for us).

**Comment by cecilia-donnelly** [comment]
See #34 for a more general form of this issue.

**Comment by cecilia-donnelly** [comment]
@xray7224: I think what this issue is really about is asking for an address to be _entered_ as a string but _saved_ as an object.  The suggestion about a library above is an implementation detail.

Mostly this will come into play on the Participant change form, but anywhere users enter an address they should be able to enter a string and have us parse it into an address object.  Does that clarify things?

**Comment by xray7224** [comment]
I was under the understanding we decided it'd be simpler and not loosing much benefit to remove the address model. I will un-assign myself from this until here is a clear answer on that.

**Comment by cecilia-donnelly** [comment]
Closing this because of #137.
