### ISSUE TITLE
"Archive" rather than "delete," throughout

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#32]
Users don't want to run the risk of accidentally deleting information, especially since they'll have a lot of volunteers doing data entry.  They'd like us to "archive," rather than "delete" information.  I'm imagining that models will have a field that governs whether they're archived or not.  If archived, objects won't show up in normal search results/lists.  Users will have the option to "unarchive" them.

Let's talk about this one, @xray7224, and clarify in the ticket.

**Comment by xray7224** [comment]
I don't think this should be too too difficult. I think how I'd go about doing this would be:

- [ ] Add a "archived" BooleanField to each model
- [ ] Create a custom [model manager](https://docs.djangoproject.com/en/1.8/topics/db/managers/) that would by default only search unarchived ones unless you explicitly asked for archived too
- [ ] Override the default `delete` method on models to by default soft delete (archive) things.
- [ ] Change the wording of the UI to say "Archive" not "Delete"
- [ ] On the UI for modifying objects, when there is an archived object show an "Unarchive" button.

There could be in addition to this a filter added when listing objects that could allow you to list both archived and unarchived objects. Currently filters aren't showing up in our templates so this would take more re-working and design and if desirable possibly should be split into it's own ticket.
