### ISSUE TITLE
Trivial cosmetic changes for Key Contacts on Institution page

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#38]
- [ ] Rename "contacts" to "key contacts."  
- [ ] Rename "Remove?" to "remove as key contact."  

Edit: moved one item to the new issue #90.

**Comment by cecilia-donnelly** [comment]
@xray7224: Very important, and possibly should be its own issue: currently the participant name shows up twice in the contacts list.  Once it is a link to the participant page and the other time it is the autocomplete field.  We should change the link to an icon of some kind instead of displaying the name twice.

**Comment by nttaylor** [comment]
Requested changes are now in. Issue #94 remains as noted in the comment above.
