### ISSUE TITLE
Theme pages

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#4]
Add SWOP logo and colors #48328F and #D9D4E8 to Swoptact.  Instead of "Contact Management System" in the header, call it "SWOP Contacts" or "SWOP Contact Management System."

Similarly, move buttons close to the items they modify.  Generally make the UI more polished.

**Comment by cecilia-donnelly** [comment]
By the way, the logo is here: https://github.com/OpenTechStrategies/lisc-ttm/blob/master/swop/images/logo-swop.jpg

**Comment by cecilia-donnelly** [comment]
Add SWOP logo to header and possibly LISC logo to footer.

**Comment by xray7224** [comment]
Based on their website (http://www.swopchicago.org/home.aspx?tab=3) the housestyle colours are:

Element               | Style
----------------------- | -------------
Background         | #F8F2EB
Border                 | #EDDDCF (10px)
Font                    | Verdana,Arial,sans-serif
hyperlinks           | #48328F

**Comment by cecilia-donnelly** [comment]
Add some space between logo and "Contacts" title.  Also, work on the styling of the new filter_horizontal setup on the events change page.

**Comment by xray7224** [comment]
We also either need to ask for a logo without a background or we need to make one ourselves. This could be something that maybe could be asked on friday when you show them our work thus far.

**Comment by kfogel** [comment]
Gave SWOP logo a transparent background, in commit 46923e2.

**Comment by cecilia-donnelly** [comment]
Closing this since we've successfully added the logo and colors to the site and further changes will take place in #18.
