### ISSUE TITLE
Change "Event" to "Action" everywhere.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/swoptact#44]
SWOP has "Actions" not "Events", so for SWOP, it needs to show up as "Action" in every user-visible place.

It is an open question whether we should also rename it in the database fields and throughout the source code, given that it will need to be configurable anyway -- other organizations may still call them "Events", or something else other than "Actions".  Perhaps we should call them "Occasions" in the code :-).

**Comment by kfogel** [comment]
All the relevant changes would be under the swoptact/ directory (except for changing the terminology in the top-level README.md, if we want to).  Obviously the `class Event` in models.py would need to change.  Beyond that, I believe that _all_ the places that need to be changed are a subset of these (already filtered down) matches:

    swoptact/settings.py:# SWOPTACT is a list of contacts with a history of their event attendance
    swoptact/formfields.py:# SWOPTACT is a list of contacts with a history of their event attendance
    swoptact/test.py:# SWOPTACT is a list of contacts with a history of their event attendance
    swoptact/mixins.py:# SWOPTACT is a list of contacts with a history of their event attendance
    swoptact/signals.py:# SWOPTACT is a list of contacts with a history of their event attendance
    swoptact/templates/admin/inline_event_participants.html:  <input type="hidden" id="event_object_id" value="{{ object_id }}" />
    swoptact/templates/admin/inline_event_participants.html:    <i>(To add participants, first save this event.)</i>
    swoptact/templates/admin/includes/event_history.html:  {% for event in events %}
    swoptact/templates/admin/includes/event_history.html:    <th><a href="{{ event.admin_change_url }}">{{ event.name }}</th>
    swoptact/templates/admin/includes/event_history.html:    <th>{{ event.date }}</th>
    swoptact/templates/admin/event_change_form.html:<script type="text/javascript" src="{% static "js/event_changes.js" %}"></script>
    swoptact/templates/admin/event_change_form.html:  {% include "admin/inline_event_participants.html" %}
    swoptact/static/js/inline_ajax.js:This page governs the sign-in sheet on the change event form.  It includes
    swoptact/static/js/inline_ajax.js:(1) find the relevant participants for a given event 
    swoptact/static/js/inline_ajax.js:(5) unlink a person from an event
    swoptact/static/js/inline_ajax.js:(8) link an existing person to this event.
    swoptact/static/js/inline_ajax.js:function getEventId() {
    swoptact/static/js/inline_ajax.js:    return document.getElementById('event_object_id').value;
    swoptact/static/js/inline_ajax.js:    var event_id = getEventId();
    swoptact/static/js/inline_ajax.js:    var url = '/api/events/'+event_id+'/participants';
    swoptact/static/js/inline_ajax.js:    var event_id = getEventId();
    swoptact/static/js/inline_ajax.js:    var url = '/api/events/'+event_id+'/available-participants';
    swoptact/static/js/inline_ajax.js:    var url = '/api/events/'+getEventId()+'/participants/'+participant_id+"/";
    swoptact/static/js/inline_ajax.js:    var event_id = getEventId();
    swoptact/static/js/inline_ajax.js:    var target_url = '/api/events/'+event_id+'/participants/'+participant_id+'/';
    swoptact/static/js/inline_ajax.js:                var url = '/api/events/'+getEventId()+'/participants/'+response.id+"/";
    swoptact/static/js/inline_ajax.js:                  select: function(event, ui) {
    swoptact/static/js/inline_ajax.js:                      event.preventDefault();
    swoptact/static/js/inline_ajax.js:                  focus: function(event, ui) {
    swoptact/static/js/inline_ajax.js:                      event.preventDefault();
    swoptact/static/js/inline_ajax.js:        function(event) {
    swoptact/static/js/inline_ajax.js:            event.preventDefault();
    swoptact/static/js/inline_ajax.js:        function(event) {
    swoptact/static/js/inline_ajax.js:            event.preventDefault();
    swoptact/static/js/inline_ajax.js:        function(event) {
    swoptact/static/js/inline_ajax.js:            event.preventDefault();
    swoptact/static/js/inline_ajax.js:        function(event) {
    swoptact/static/js/inline_ajax.js:            event.preventDefault();
    swoptact/static/js/inline_ajax.js:        function(event) {
    swoptact/static/js/inline_ajax.js:            event.preventDefault();
    swoptact/static/js/inline_ajax.js:        function(event) {
    swoptact/static/js/inline_ajax.js:            event.preventDefault();
    swoptact/static/js/inline_ajax.js:        function(event) {
    swoptact/static/js/inline_ajax.js:            event.preventDefault();
    swoptact/static/js/inline_ajax.js:        function(event) {
    swoptact/static/js/inline_ajax.js:            event.preventDefault();
    swoptact/static/css/swoptact.css: * SWOPTACT is a list of contacts with a history of their event attendance
    swoptact/models.py:# SWOPTACT is a list of contacts with a history of their event attendance
    swoptact/models.py:    """ Tags act as descriptors for such models as Event """
    swoptact/models.py:    """ Representation of a person who can participate in a Event """
    swoptact/models.py:    def events(self):
    swoptact/models.py:        """ List of all events participant is in """
    swoptact/models.py:        return Event.objects.filter(participants__in=[self]).all()
    swoptact/models.py:class Event(models.Model, mixins.AdminURLMixin, SerializeableMixin):
    swoptact/wsgi.py:# SWOPTACT is a list of contacts with a history of their event attendance
    swoptact/views.py:# SWOPTACT is a list of contacts with a history of their event attendance
    swoptact/views.py:        they are deleted to prevent objects being created not associated or used
    swoptact/views.py:class EventParticipantsAPI(APIMixin, generic.DetailView):
    swoptact/views.py:    Provides a list of all participants linked to a event
    swoptact/views.py:    model = models.Event
    swoptact/views.py:        """ Retrival of an existing event """
    swoptact/views.py:class EventAvailableAPI(APIMixin, generic.DetailView):
    swoptact/views.py:    Provides a list of all participants that are not linked to an event
    swoptact/views.py:    model = models.Event
    swoptact/views.py:        """ Retrival of an existing event """
    swoptact/views.py:class EventLinking(APIMixin, generic.DetailView):
    swoptact/views.py:    Provides a mechanism to link and unlink Participants from Events
    swoptact/views.py:    model = models.Event
    swoptact/views.py:        # Remove from the event
    swoptact/views.py:        # Remove from the event
    swoptact/__init__.py:# SWOPTACT is a list of contacts with a history of their event attendance
    swoptact/widgets.py:# SWOPTACT is a list of contacts with a history of their event attendance
    swoptact/modelfields.py:# SWOPTACT is a list of contacts with a history of their event attendance
    swoptact/admin.py:# SWOPTACT is a list of contacts with a history of their event attendance
    swoptact/admin.py:from swoptact.models import Address, Participant, Event, Institution, Contact, Tag
    swoptact/admin.py:            "event_form": modelform_factory(Event, exclude=("description", "participants", "is_prep")),
    swoptact/admin.py:    """ Admin UI for participant including listing event history """
    swoptact/admin.py:    readonly_fields = ("event_history", "event_history_name", )
    swoptact/admin.py:        ("Personal Event History", {
    swoptact/admin.py:            "fields": ("event_history",),
    swoptact/admin.py:    def event_history_name(self, obj):
    swoptact/admin.py:        """ Name of event history fieldset """
    swoptact/admin.py:        return "Events that {first} {last} attended".format(
    swoptact/admin.py:    def event_history(self, obj):
    swoptact/admin.py:        """ HTML history of the events attended by the participant """
    swoptact/admin.py:        template_name = "admin/includes/event_history.html"
    swoptact/admin.py:        event_history_template = loader.get_template(template_name)
    swoptact/admin.py:            "events": obj.events,
    swoptact/admin.py:        return event_history_template.render(context)
    swoptact/admin.py:    # To prevent django from distorting how the event_history method looks tell
    swoptact/admin.py:    event_history.allow_tags = True
    swoptact/admin.py:class EventAdmin(admin.ModelAdmin):
    swoptact/admin.py:    change_form_template = "admin/event_change_form.html"
    swoptact/admin.py:class EventModelForm(autocomplete_light.ModelForm):
    swoptact/admin.py:        model = Event
    swoptact/admin.py:admin.site.register(Event, EventAdmin)
    swoptact/migrations/0030_auto_20150430_1917.py:            model_name='event',
    swoptact/migrations/0030_auto_20150430_1917.py:            model_name='event',
    swoptact/migrations/0017_auto_20150324_1509.py:            model_name='event',
    swoptact/migrations/0017_auto_20150324_1509.py:            model_name='event',
    swoptact/migrations/0017_auto_20150324_1509.py:            model_name='event',
    swoptact/migrations/0017_auto_20150324_1509.py:            model_name='event',
    swoptact/migrations/0017_auto_20150324_1509.py:            model_name='event',
    swoptact/migrations/0028_auto_20150429_1248.py:            model_name='event',
    swoptact/migrations/0028_auto_20150429_1248.py:            model_name='event',
    swoptact/migrations/0028_auto_20150429_1248.py:            model_name='event',
    swoptact/migrations/0016_auto_20150324_0833.py:            model_name='event',
    swoptact/migrations/0016_auto_20150324_0833.py:            model_name='event',
    swoptact/migrations/0022_event_terminal.py:            model_name='event',
    swoptact/migrations/0022_event_terminal.py:            field=models.ForeignKey(blank=True, null=True, to='swoptact.Event'),
    swoptact/migrations/0023_auto_20150407_1358.py:        ('swoptact', '0022_event_terminal'),
    swoptact/migrations/0023_auto_20150407_1358.py:            model_name='event',
    swoptact/migrations/0023_auto_20150407_1358.py:            new_name='terminal_event',
    swoptact/migrations/0027_auto_20150429_1222.py:            model_name='event',
    swoptact/migrations/0027_auto_20150429_1222.py:            old_name='terminal_event',
    swoptact/migrations/0027_auto_20150429_1222.py:            model_name='event',
    swoptact/migrations/0001_initial.py:            name='Event',
    swoptact/migrations/0001_initial.py:            model_name='event',
    swoptact/migrations/0007_auto_20150310_1449.py:            model_name='event',
    swoptact/migrations/0018_auto_20150324_1553.py:            model_name='event',
    swoptact/migrations/0029_add_groups.py:# SWOPTACT is a list of contacts with a history of their event attendance
    swoptact/migrations/0019_auto_20150402_1640.py:            model_name='event',
    swoptact/migrations/0019_auto_20150402_1640.py:            model_name='event',
    swoptact/migrations/0019_auto_20150402_1640.py:            model_name='event',
    swoptact/migrations/0019_auto_20150402_1640.py:            model_name='event',
    swoptact/migrations/0019_auto_20150402_1640.py:            model_name='event',
    swoptact/migrations/0019_auto_20150402_1640.py:            model_name='event',
    swoptact/migrations/0008_auto_20150317_1335.py:            model_name='event',
    swoptact/decorators.py:# SWOPTACT is a list of contacts with a history of their event attendance
    swoptact/urls.py:# SWOPTACT is a list of contacts with a history of their event attendance
    swoptact/urls.py:        url(r"^events/(?P<pk>\w+)/", include(patterns("",
    swoptact/urls.py:            url(r"^participants/$", views.EventParticipantsAPI.as_view(), name="api-event-participants"),
    swoptact/urls.py:            url(r"^available-participants/$", views.EventAvailableAPI.as_view(), name="api-event-available"),
    swoptact/urls.py:            url(r"participants/(?P<participant_id>\w+)/$", views.EventLinking.as_view(), name="api-event-linking"),

**Comment by cwebber** [comment]
Luckily Django makes this pretty easy without any migration or major code overhaul.  Done in 61bacf8
