### ISSUE TITLE
Sign-in sheet: Freeze header row

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#46]
The header row of the sign in sheet should remain visible ("frozen") as users scroll down through attendees.  

* I tried this https://github.com/markmalek/Fixed-Header-Table but it didn't work with our dynamically created table
* Useful, if complex: http://tympanus.net/codrops/2014/01/09/sticky-table-headers-columns/ Relies on the throttle+debounce plugin (?)

**Comment by cwebber** [comment]
I wonder if it could be possible to take a route similar to the second route, build a copy of the header field that hovers over the original header row in JS, and floats attached to the top of the page on scroll.  It might be possible to do without any extra libraries.  I've never tried duplicating a table row and having it "float" dynamically over the rest of its content before... it could be tricky.

**Comment by nttaylor** [comment]
Closing following 51b1ba6.

**Comment by cecilia-donnelly** [comment]
@nttaylor has managed this for change lists (yey!) but the sign-in sheet will probably require a slightly different solution.

**Comment by nttaylor** [comment]
Closing following 21bd5e5b
