### ISSUE TITLE
Action: remove delete button

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#52]
Users don't see any reason to have a delete (or archive) button on the Action page.

**Comment by cwebber** [comment]
Is this the delete button in the lower left corner, or the delete on the "actions" list for unlinking an ajax'ily added user?  I'm uncertain because this says "action page"... does this mean "action column"?

**Comment by cwebber** [comment]
Relatedly, that would resolve #61 :)

**Comment by cwebber** [comment]
I can do this one regardless once clarified.

**Comment by cecilia-donnelly** [comment]
@cwebber, ah, yes.  This is called "Action" because of issue #44.  It means removing the delete button in the lower left corner, not the "undo" button you mentioned.

**Comment by cwebber** [comment]
Done in 919a96f
