### ISSUE TITLE
Install: update INSTALL.md with instructions for installing on a (Debian) server

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#53]
Currently INSTALL.md assumes that the installation is happening locally in a virtual environment.  We want to be able to install the app on a remote server as well.

**Comment by xray7224** [comment]
I have done most of this however i ran into #56. I suspect this will all work once #56 is resolved, but it should be checked. I have also added a apache 2.4 configuration file to the repository.

**Comment by kfogel** [comment]
Finished in commit 2f54c4973fc.
