### ISSUE TITLE
Make autocompletion work with custom template

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#54]
As mentioned in commit 154150e, the autocompletion library doesn't work out of the box with custom templates (e.g. templates/admin/inline_event_participants.html).  We want to use it for several fields on the event page, notably tags, location, and the participants's names in the sign-in sheet.  It might be that we can't use the autocomplete_light library with the sign-in sheet (since that whole section of the page is dynamically generated), but we should be able to use it at least with the tags and location fields, which are not part of the sign in sheet.

**Comment by cecilia-donnelly** [comment]
Possible duplicate of #76, #77, #48.  At least related to all of those!

**Comment by cwebber** [comment]
You might want to look at how the django [widget rendering template works](https://github.com/yourlabs/django-autocomplete-light/blob/master/autocomplete_light/templates/autocomplete_light/widget.html) and see if you can use it somehow.

**Comment by cecilia-donnelly** [comment]
@cwebber thanks, will do!

**Comment by cecilia-donnelly** [comment]
Since we've closed #76 and #77, and @cwebber is actively working on #48, I think this issue can be closed as a duplicate.  It turned out that loading jquery multiple times was causing this bug.
