### ISSUE TITLE
Remove django_google_maps if we're not using it.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/swoptact#59]
If we're not using the Django Google Maps app (`swoptact/django_google_maps`), we should remove it.  Otherwise it will continue to cause problems like the one mentioned in issue #55 and solved with a workaround in commit 63fe801af.

**Comment by cecilia-donnelly** [comment]
@xray7224, I think you talked to @kfogel about this in IRC.  The django_google_maps app is entangled in our migrations.  What's the right way to remove it entirely?
