### ISSUE TITLE
Add new address, participant, action, etc. from places where each is linked as a foreign key

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#60]
There are comments about this in #29 and in #34, but this specific issue has been lost in the shuffle.  When we are creating a new participant or institution (for example) we probably also want to create a new address.  We should be able to create that new address (or other object) on the same page, in the same text box.

**Comment by kfogel** [comment]
Some comments after discussion with @cecilia-donnelly today:

It may not be worth it to make Address be a first-class object type -- string might sufficient, and would be simpler.  Then on, e.g., the Institutions page, the Address would just be entered as a string, and saved as a string.  We can still to autofill completion, both to save people keystrokes and to make it more likely that when the same address (as some existing address) is intended, then the same exact text gets entered.  But none of that requires object-hood internally; it can be done with Addresses as strings.

@xray7224 would love your thoughts.  Happy to discuss in IRC too.
