### ISSUE TITLE
"Undo" is a confusing button name

### ISSUE THREAD

**Issue by cwebber** [OpenTechStrategies/swoptact#61]
I made a change which was accidental, updated it, then decided I made a mistake and noticed there was a convenient "update" button on the ajax'y actions of inline attendee editing on event administration.  So I hit "undo", but instead of undo'ing the thing I just did, it removed the entry.

That's not what undo normally means in computer programs, so I was confused.  Then I remembered I implemented this and it was a name change!

Are we sure we want "undo" to map to "remove"?  That could be very confusing for users.

**Comment by cecilia-donnelly** [comment]
I agree that it's confusing.  @kfogel and I talked to the users about it and they chose it, so I suppose ultimately it'll be a training issue.  Let's leave it as is for now and we can check back with them next time we meet.

**Comment by cecilia-donnelly** [comment]
See #132.
