### ISSUE TITLE
Missing fields doesn't show errors, nothing happens

### ISSUE THREAD

**Issue by cwebber** [OpenTechStrategies/swoptact#63]
When a server error happens, instead of the error form being filled in, nothing happens.  The user is given no indication that either their input was invalid or that something wrong happened on the server... nothing happens, which is very confusing.

**Comment by cwebber** [comment]
There's space left in this in the design so that errors should be shown, but they aren't being so.

**Comment by cecilia-donnelly** [comment]
Fixed in ff7b60b and cccae6d.  Once #87 is done, we'll have to add specific errors for institutions.
