### ISSUE TITLE
Remove plus signs and pencils next to all fields where they exist

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#68]
This is implied by #60, but we might as well state it explicitly.  We want to create objects in the existing text field wherever possible and avoid adding new UI elements that might confuse users.

**Comment by cwebber** [comment]
Do we want to remove the unicode checkboxes and etc characters on the save/cancel buttons on the inline ajax form too and have it be just text?  Or is this just "remove the image buttons that activate editing / removing" not "remove decoration from button labels"?

**Comment by cecilia-donnelly** [comment]
This is (a) "remove the image buttons that activate editing / removing."  Essentially, wherever a field is a foreign key Django has given us the edit/add icons.  The plus sign opens a new window to create a new object, and I'm not sure what the pencil does.  Basically, we never want to open that new window.  We want to be able to create the object from the text field (see #60), so the pencil/plus sign will go away.  This is really just a consequence of #60 and shouldn't affect the sign-in sheet at all.
