### ISSUE TITLE
Tags: text box is too large and doesn't warn when name exceeds limit

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/swoptact#72]
Tag names can only be up to 10 characters long.  We should alert users when they near and/or exceed this limit (before they submit the form). (like Twitter!)

**Comment by xray7224** [comment]
I have set `size=10` which is the max_length value (I've actually just set it to whatever the max length is). This however seems to display a few characters wide in Firefox and Chrome. The [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Attributes) on this seems to state that it should be the length in characters (as it's a text field):
 
> The initial size of the control. **This value is in pixels unless the value of the type attribute is text or password, in which case, it is an integer number of characters.** Starting in HTML5, this attribute applies only when the type attribute is set to text, search, tel, url, email, or password; otherwise it is ignored. In addition, the size must be greater than zero. If you don't specify a size, a default value of 20 is used.

I left it as 10 as I'm not sure how other browsers will handle it, it should be much closer to the length you can actually enter at least. I'm not sure if we should close this or not, maybe @kfogel or @cecilia-donnelly want to have a look and decide if will be clear to the user.

**Comment by cecilia-donnelly** [comment]
@xray7224: 
The length of the box looks great, but we should add an error if users try to keep typing more than 10 characters, so that it's clear to them what is going on.
