### ISSUE TITLE
Sign-in sheet: hitting Return while editing a row causes another row to open for editing too.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/swoptact#88]
To reproduce:

1. Go to Swoptact Administration -> Events -> "Demo Event" (http://localhost:8000/swoptact/event/8/ in our sample data)
2. Click Edit for "Daria Lagos"
3. Enter some numbers in the phone number field but *do not* click Done
4. With cursor still active in phone number field, hit the Return key

Now you should see a different row -- probably the first one, "Lauren Russo" open up for editing too!  Not exactly an expected behavior :-).

There are really two misbehaviors here: the fact that Lauren Russo's row opened for editing, and the fact that Return didn't do anything for Daria Lagos's row where editing was active at the time Return was hit.  I expected Daria Lagos's row to be saved -- i.e., as if I had clicked "Done".

**Comment by cwebber** [comment]
Sorry, I didn't mean to assigne the milestone!

**Comment by cwebber** [comment]
Reassigned to myself per convo w/ @cecilia-donnelly on IRC

**Comment by cwebber** [comment]
Done in 42ae01c
