### ISSUE TITLE
Event: calendar link broken in Chrome 

### ISSUE THREAD

**Issue by nttaylor** [OpenTechStrategies/swoptact#92]
In Chrome v. 43.0.2357.124 (64-bit) on Mac OS X 10.7.5 as of commit c7172d01cc5 with no local changes:

![screen shot 2015-06-11 at 3 32 03 pm](https://cloud.githubusercontent.com/assets/12848962/8117681/bc4a8ece-104f-11e5-97e6-36b9614d2844.png)

**Comment by cecilia-donnelly** [comment]
@nttaylor, you're probably the only one who can reproduce this, so I'm assigning you for now.

**Comment by nttaylor** [comment]
Fixed in commit above.
