### ISSUE TITLE
login label effaced in Chrome

### ISSUE THREAD

**Issue by nttaylor** [OpenTechStrategies/swoptact#93]
In Chrome v. 43.0.2357.124 (64-bit) on Mac OS X 10.7.5 as of commit c7172d0 with no local changes:

![screen shot 2015-06-11 at 5 13 08 pm](https://cloud.githubusercontent.com/assets/12848962/8119715/30678624-105d-11e5-8b98-f836c9abf9b3.png)

**Comment by cecilia-donnelly** [comment]
@nttaylor fixed this in commit 34c0a67, so I'm closing it.
