### ISSUE TITLE
Key Contacts table not styled like others

### ISSUE THREAD

**Issue by nttaylor** [OpenTechStrategies/swoptact#99]
The "Key Contacts" table, which is the lower table on the Change Institution page, is not styled like the other tables. It has no border stripe around the edge and content is jammed up against the left-hand side. Compare it to the upper table in the screenshot:

![screen shot 2015-06-18 at 5 05 10 pm](https://cloud.githubusercontent.com/assets/12848962/8243412/745b41b6-15dc-11e5-96f7-4ba6bd7c390b.png)

**Comment by cecilia-donnelly** [comment]
After completion of #94, this table looks completely different.  Closing this accordingly.
